### ISSUE TITLE
FR: few things

### ISSUE THREAD

**Issue by witnes0417** [jgchristopher/obsidian-clipper#18]
- support clipped image to obsidian( copy an image then "send" short cut)
- support comment feature( do not need jump to obsidian just clip and comment)
- support short cuts in the browser( select then "comment"short cut then comment, and always in current page)

**Comment by jgchristopher** [comment]
I will look into allowing comments, though I was trying to limit the code actually in the bookmarklet. 

I just released version 0.0.5 which has settings to control if obsidian should be opened when clipping to any of the supported note types (daily, weekly, or the new topic notes).

Currently, if you highlight an image and click the bookmarklet, it will link to the image in the note. Is this not what you are looking for?

>support short cuts in the browser( select then "comment"short cut then comment, and always in current page)
I am not sure what you mean by this. By current page, do you mean current opened obsidian note? The Topic/Subject note type I just added may interest you. If you open the command palette in Obsidian, type `obsidian clipper note`, select `Obsidian Clipper: Note Bookmarklet`, this will open a modal with a bookmarklet to clip to the currently open note.

**Comment by witnes0417** [comment]
- first, my apology to confuse you
- for the image: I mean to download the image like the image copy-paste feature in obsidian. the image will be stored in the attachment directory. in my workflow, I'd like to use screenshots /snippets to take quick notes. so I'd like to copy an image and then from the system clipboard to send to obsidian via this plugin.
- for the current page: I mean in the browser page. I like vim feature a lot, so i use vimium c in chrome, that is why I need a keybinding feature of this plugin.

**Comment by jgchristopher** [comment]
> support short cuts in the browser( select then "comment"short cut then comment, and always in current page)

Chrome supports this directly for extensions and the plugin now supports installing the bookmarklet as an extension.

**Comment by jgchristopher** [comment]
I am going to close this. The latest release has the a 'add comment' feature in advanced -> Experimental Settings. Still need to work on it, but it is a start. 

The keybinding part can possibly be fixed by installing the Chrome-based extension and setting a keybinding via Chrome. 

You can use the https://github.com/aleksey-rezvov/obsidian-local-images plugin to have any clipped images downloaded locally.
