### ISSUE TITLE
Selecting an image with text ouputs nothing

### ISSUE THREAD

**Issue by SynapticDreams** [jgchristopher/obsidian-clipper#20]
If selecting a heading, some text and an image, the bookmarklet does not bring anything across to obsidian.

If you select just the image, it brings that across.
If you select the H1 and the text it brings that across.

Using latest versions as of 1st April 2023 for Advanced Tables in Obsidian, Daily Notes and Obisidian Clipper .

**Comment by jgchristopher** [comment]
Can you share the website where this wasn't working? Also, can you share what browser you are using?

**Comment by SynapticDreams** [comment]
Website was https://trickmenot.ai/best-a-i-copywriting-and-seo-tools-for-every-level-and-every-budget/ and browser was Chrome 111 on Windows 11

**Comment by jgchristopher** [comment]
Should be fixed in 0.0.7 #24
