### ISSUE TITLE
Embeded YouTube Video not coming across to Obsidian

### ISSUE THREAD

**Issue by SynapticDreams** [jgchristopher/obsidian-clipper#22]
The embeded YouTube video inside a page is causing the output to not come across if selected with text. I've tried also just choosing the YouTube video without luck.

Eg. Site tested [here](https://trickmenot.ai/best-a-i-copywriting-and-seo-tools-for-every-level-and-every-budget/)

Latest versions as of 1st of April 2023 for Advanced Tables, Obisidian Clipper and Obsidian. Also using new bookmarklet.

**Comment by SynapticDreams** [comment]
Browser was Chrome 111 on Windows 11

**Comment by jgchristopher** [comment]
Should be fixed in `0.0.7` #24
