### ISSUE TITLE
Can't copy the bookmarklet on mobile device. 

### ISSUE THREAD

**Issue by guihasparyk** [jgchristopher/obsidian-clipper#23]
Since I can't acess my PC, it seems impossible to copy the the bookmarklet through my android mobile phone on the plugin settings inside Obsidian.

Can some Dev help me to get that link copied?

**Comment by jgchristopher** [comment]
I’m not sure if this will work on android but here is how it works on iOS. 

![RPReplay_Final1682128466](https://user-images.githubusercontent.com/35281/233757803-f18ed927-23f0-4213-beba-ad10fff5368d.gif)

**Comment by guihasparyk** [comment]
Thanks for the tip, BTW awesome Workflow you have there.

Unfortunately I couldn't make it work the drag and drop, even on multi-tasking screen on my Huawei P20 Lite. 

But I managed to install an app called [Touchpad for Big Phone & Tab](https://play.google.com/store/apps/details?id=com.mpointer.touchpad.bigphones) that puts a touch pad and a cursor on the screen and simulate the drag and drop gesture.

So it worked. But took me some hastle to find that app, testing all the cursor like apps. LoL.

If the developer could give us an option to copy those JSs would great though.

**Comment by jgchristopher** [comment]
In the next update I am adding new commands to copy either the vault bookmarklet or a specific note bookmarklet to the clipboard so you can then just create a new bookmark and past in the code.
