### ISSUE TITLE
"How to use" is outdated

### ISSUE THREAD

**Issue by 40rn05lyv** [jgchristopher/obsidian-clipper#26]
Hi. default.gif provides outdated information about how to use this plugin. 

According to gif, I should drag a link into a bookmarks bar. However, there's no such link.

In UI a banner mentions a browser extension in "Browser settings tab", however I don't see such tab in Obsidian settings.

**Comment by jgchristopher** [comment]
Thanks for the feedback!

I will be recording an updated video later this week. Just to clarify, you don't see something like what is in the screenshot below? If not, what OS are you using?

<img width="828" alt="CleanShot 2023-05-09 at 13 56 42@2x" src="https://github.com/jgchristopher/obsidian-clipper/assets/35281/8a5cc7d9-e9ac-4682-95dd-f4df93ec70cd">

**Comment by 40rn05lyv** [comment]
OS - Windows 10

![image](https://github.com/jgchristopher/obsidian-clipper/assets/1200215/7cebb706-d0a0-4ab8-b7b4-2fd35483ddc0)

**Comment by jgchristopher** [comment]
Interesting, I will take a look.Can you also share the version of Obsidian and verify the version of the plugin you have like below? Thanks!

<img width="819" alt="CleanShot 2023-05-12 at 08 41 06@2x" src="https://github.com/jgchristopher/obsidian-clipper/assets/35281/b2378765-5e9e-4082-9044-33f5fe5eb270">

<img width="259" alt="CleanShot 2023-05-12 at 08 41 26@2x" src="https://github.com/jgchristopher/obsidian-clipper/assets/35281/b5a033da-60eb-43b7-aa84-8dea56fae86b">

**Comment by 40rn05lyv** [comment]
Obsidian version is 1.2.8, the latest
![image](https://github.com/jgchristopher/obsidian-clipper/assets/1200215/8796025d-742c-4f2d-931a-024df2648891)

Plugin version 0.1.0
![image](https://github.com/jgchristopher/obsidian-clipper/assets/1200215/672bbee2-d7f5-48ff-8e4f-2c23a155092d)

**Comment by jgchristopher** [comment]
I tested today on a brand new Obsidian installation on Windows 10, and things worked as expected. 

I'm at a loss as to what could be wrong. 

Would you mind uninstalling and reinstalling to see if that makes any difference?

If that doesn't work I would need you to open the developer console and see if there are any errors logged there. 

Thanks again!

**Comment by jinsihou19** [comment]
<img width="805" alt="image" src="https://github.com/jgchristopher/obsidian-clipper/assets/11626168/6e2a5a31-d16a-4e52-913b-4e962411cd3e">
same to me

**Comment by jgchristopher** [comment]
@40rn05lyv, @jinsihou19 Would you mind sharing the other plugins you have installed? I can't reproduce the issues you are seeing, and I would like to see if it is related to another plugin.

**Comment by jgchristopher** [comment]
Actually, I just installed the plugins I noticed in @40rn05lyv screenshot, and I now have the same issue, so progress.

**Comment by jgchristopher** [comment]
Ok, I have narrowed it down to the Text Generator plugin. I need to dig in and see what is going on.

**Comment by jgchristopher** [comment]
@jinsihou19 @40rn05lyv This should now be fixed in the latest version. I still need to update the overview video. Thanks for reporting your issue!
