### ISSUE TITLE
Template paths are lower-cased even if it has mixed cases.

### ISSUE THREAD

**Issue by trustin** [jgchristopher/obsidian-clipper#30]
I keep my templates under `Templates/` directory and my clipped entry template is at `Templates/Clipping.md`.  When I specify it in the plugin's preferences, it automatically lower-cases it into `templates/clipping.md`. I suspect this will not work when a user uses Obsidian on a case-sensitive filesystem.

**Comment by trustin** [comment]
That's interesting. Other extensions I use show the cases correctly. Periodic Notes for example:

<img width="762" alt="image" src="https://github.com/jgchristopher/obsidian-clipper/assets/173918/a4a8505d-b046-47d7-8cd3-212fd8efbdf2">

**Comment by jgchristopher** [comment]
Actually, I was doing this and I believe you were right that it would probably cause problems on case sensitive file systems. 

```typescript
dataProvider().forEach((file) => {
   if (file.path.toLowerCase().startsWith(initialValue.toLowerCase())) {
	    storageArr = [...storageArr, file.path.toLowerCase()];
    }
});
```

going to push a change that removes the `.toLowerCase()` when adding to the `storageArr` which is what populates the autosuggest. 

Thanks for the feedback!
