### ISSUE TITLE
Unable to copy the url from the browser section in obsidian on mac 

### ISSUE THREAD

**Issue by Eytan3** [jgchristopher/obsidian-clipper#32]

**Comment by jgchristopher** [comment]
There are a couple of ways to get the bookmarklet into your bookmarks. 

1. You can drag the link to your bookmark bar
2. If you use the command palette in obsidian and select the `Obsidian Clipper: Vault Bookmarklet to Clipboard` command it will automatically copy the bookmarklet. You can then create a bookmark and paste the code in for the link. 

<img width="702" alt="CleanShot 2023-05-18 at 18 44 15@2x" src="https://github.com/jgchristopher/obsidian-clipper/assets/35281/96ee8de7-72a5-4da4-9ae7-beff517d3a8b">

**Comment by Eytan3** [comment]
Thank you so much John!

‫בתאריך יום ו׳, 19 במאי 2023 ב-2:45 מאת ‪John Christopher‬‏ <‪
***@***.***‬‏>:‬
