### ISSUE TITLE
FR: Allow clipping to other periodic notes

### ISSUE THREAD

**Issue by brimwats** [jgchristopher/obsidian-clipper#4]
I use a weekly note instead of a daily one; I'm wondering if this can be used to capture to that instead, or perhaps even an inbox note I specify?

**Comment by jgchristopher** [comment]
I will take a look at what options I can add.

**Comment by jgchristopher** [comment]
I am going to look at this over the weekend.

**Comment by jgchristopher** [comment]
@brimwats Do you use a plugin for weekly note management?

**Comment by brimwats** [comment]
just periodic notes

**Comment by jgchristopher** [comment]
Perfect. That makes things easy.

**Comment by jgchristopher** [comment]
Weekly notes are now supported.
