### ISSUE TITLE
Bug: Clipper overwrites previous clipping with most recent clipping if there's no new line in your template file

### ISSUE THREAD

**Issue by benvenker** [jgchristopher/obsidian-clipper#41]
The last link in the links list is being continually overwritten with the most recently clipped link. I fixed this by just adding a carriage return after the last line in my template file.

This may not be the case for all templates. Mine is:
```
- [ ] [{{title}}]({{url}}) {{tags}}

```

**Comment by jgchristopher** [comment]
Thanks for reporting. I will add a fix to account for that situation.

**Comment by jgchristopher** [comment]
I updated this in the latest release to add a newline to help make sure it doesn't happen to anyone else.
