### ISSUE TITLE
Support for {{date}}

### ISSUE THREAD

**Issue by codeRSH** [jgchristopher/obsidian-clipper#43]
Hi, 

Thanks for this great plugin. 

I am using this browser extension to clip web content into my Weekly Notes. 

The {{time}} template works fine. But for some reason using {{date}} in the Template file to get the current date doesn't work .

Neither does Templater Plugin's `<% tp.date.now( ) %>` 

I want to if I am doing something wrong, or is the {{date}} not supported? If not supported, can you please work to enable {{date}} support? 

Thanks!
RavS

**Comment by jgchristopher** [comment]
Currently there is just a {{ time }} template variable and that format of that is controlled by the `Date Time Format` configuration in the settings under `Base -> Common Settings`. The format you select there will be used in all instances of the `{{ time }}` template variable. The difference format options are explained [here](https://momentjs.com/docs/#/displaying/format/). 

Does this solve your problem? or are you wanting to use both a {{ time }} and a {{ date }}. I believe this is the case you are looking for, which would be easy to add.

**Comment by codeRSH** [comment]
Hi John,

Yes I am looking to use both {{ date }} and {{ time }} variables together in the Clipper Template.

Will it be possible for you to enable {{ date }} template variable?

Thanks
RavS

**Comment by jgchristopher** [comment]
Yes, I am working on a new release and I will add this to that release.

**Comment by codeRSH** [comment]
Thanks so much!

Regards,
RavS

**Comment by jgchristopher** [comment]
This was added in the lastest release. Please let me know if anything comes up.

**Comment by codeRSH** [comment]
![image](https://github.com/jgchristopher/obsidian-clipper/assets/4953198/b34d87d9-0a96-4be3-adbe-b76cab70abce)

Works. Thanks again!
Regards, 
RavS
