### ISSUE TITLE
Missing manifest version so it will not install

### ISSUE THREAD

**Issue by twhite96** [jgchristopher/obsidian-clipper#45]
1. there is no place in the README to find out where the zip file is.
2. I went to the releases page and downloaded the zip file
3. I unzipped the file
4. I loaded the unpacked extension in Arc in Developer Mode
5. This is the error I got:

![CleanShot 2023-10-01 at 22 08 32@2x](https://github.com/jgchristopher/obsidian-clipper/assets/7698292/30f2b695-d5e5-40cc-b740-e33d6f5ebe92)

**Comment by twhite96** [comment]
I tried adding the missing key/value pair, it uploaded but there were still more errors.

**Comment by jgchristopher** [comment]
Is this regarding installing the plugin to obsidian or installing the chrome extension downloaded from within Obsidian?

**Comment by HacDan** [comment]
I think the issue here is trying to load the obsidian extension into a Chromium-based browser. 

Where would the link be to download the Chrome Extension? I think that's what @twhite96 is trying to do.

**Comment by twhite96** [comment]
@HacDan Yeah I found the release but I can't load the unpacked extension in Arc browser on my M1 Mac Mini running Sonoma. Arc is Chromium based as well

**Comment by HacDan** [comment]
This repo and that release is the Obsidian extension. 

@jgchristopher has another repo for generating the chrome extension but I'm unable to find it hosted anywhere. May need to clone and run yourself. I'm not sure. 

https://github.com/jgchristopher/obsidian_clipper_extension_maker

**Comment by jgchristopher** [comment]
I am working on a documentation site that will hopefully clear up any confusion. The extension code is used as a service by the Obsidian plugin to generate a chrome extension for your vault or specific note.

**Comment by jericjan** [comment]
Idk why nobody mentioned this but you're supposed to go to the plugin's settings in Obsidian to generate the customized Chromium extension. I don't quite understand the reason for making a customized extension. I haven't looked into the code yet but wouldn't the difference just be a variable of where your Vault is?

**Comment by jgchristopher** [comment]
The plugin packages the extension up with configurations from the plugin, which include markdown settings, vault or note to clip to, and if comments should be collected when clipping (this is currently experimental). 

It also provides the benefit of doing everything right from the obsidian plugin.

**Comment by HacDan** [comment]
Downside is with no clear documentation or onboarding flow, I had no idea to look for something like this to generate what would normally be installed from a web store or web page. 

Is there a way to decouple this and have the plugin be more generic and have the settings be placed by the user? I realize we're working with tradeoffs here, but generating a Chrome Extension from an Obsidian plugin with no onboarding workflow seems more cumbersome than configuring a plugin that is installed from the webstore, or even a download from somewhere.

Just my $0.02

**Comment by jgchristopher** [comment]
I completely agree that the documentation has been lacking, and that is what I am currently working on. I just released a new site with the start of documentation and an introductory "Getting Started" video. To your point, it doesn't cover the Chrome extension, but I will add more videos to cover those different use cases.

https://docs.obdisianclipper.com

**Comment by HacDan** [comment]
> https://docs.obdisianclipper.com

https://docs.obsidianclipper.com

Looks like there's a typo, for anyone finding this from Google, this is the correct documentation link.
