### ISSUE TITLE
Can't find heading

### ISSUE THREAD

**Issue by BKR-dev** [jgchristopher/obsidian-clipper#47]
Hey, just found your project and i wanted to set it up, thanks to your video but whenever i want to clip something "Can't find heading" 

I left all settings default and did not add a template file to the clipper config so i dont know what the issue is but if i interpret it correctly it cannot find any heading. So i setup a quick little server with a html page and various h1-6 tags and none of them could be clipped. 

No idea whats the issue is but i really like the idea to quick and easy add things from the browser to a daily note, so i would love to use this!

Cheers.

**Comment by jgchristopher** [comment]
That error usually occurs when it is trying to add the clipping to your daily note and it can't find the heading you have configured. 

In your settings, what do you have in the 'Daily Note Header' setting? Is this a level 1 header (#) in your daily note?

If you look [here](https://docs.obsidianclipper.com/docs/base/daily_note). This has the value 'Daily Log' and in my daily note I have a level 1 header (# Daily Log).

**Comment by BKR-dev** [comment]
Thanks for the reply, i have set it to the `#` header in the daily note template and the clipper template and it still doesnt work. it seems that there are some settings from the daily note that need to match the clipping settings so it all works as intended. 

i dont know which ones there are or how i need to match the daily notes templates to clipper templates so i can get it to work. since there are no infos on what is needed to configure where and why im not bothering with this further. 

i like the idea a lot but i simply cannot get it working due to missing information on configuration between the plugin and the daily notes.

**Comment by jgchristopher** [comment]
@BKR-dev Sorry for the frustration. There is a new version that may help with your issue.

**Comment by BKR-dev** [comment]
@jgchristopher thanks, will take a look! (sorry for being such a brat, i was way too hyped and tried to make it work in a small time windows between things and got carried away, apologies!)
