### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by neuromaancer** [jgchristopher/obsidian-clipper#49]
It would be better if we can use it in FireFox.

**Comment by jgchristopher** [comment]
The bookmarklet should work fine in FireFox.

**Comment by alfredbuehler** [comment]
> The bookmarklet should work fine in FireFox.

But it doesn't. Nothing happens. :cry:

**Comment by jgchristopher** [comment]
Can you share the version of Firefox that you are using and any other information you are comfortable sharing? I just tested the latest version, and the bookmarklet works as expected.

If you know how to look at the developer tools (Tools -> Browser Tools -> Web Developer Tools) and see if there are any errors under the Console tab would be helpful.

**Comment by alfredbuehler** [comment]
Thanks for your answer. For me, it's solved now. My Firefox (119.0.1, Linux) was unable to handle the obsidian:// protocol.
