### ISSUE TITLE
The Plugin is mindblowing but it isnt working with Arc Browser 

### ISSUE THREAD

**Issue by paranjay245** [jgchristopher/obsidian-clipper#5]
if there could be any solution about it then please solve the issue! thank you soo much

hey, here’s an invite to Arc, the browser I was telling you about! - it is mac only browser it isnt based on bookmark based 

https://arc.net/gift/694f6ca5

**Comment by paranjay245** [comment]
> if there could be any solution about it then please solve the issue! thank you soo much
> 
> hey, here’s an invite to Arc, the browser I was telling you about! - it is mac only browser it isnt based on bookmark based
> 
> https://arc.net/gift/694f6ca5

I Had Asked Developers  about the issue but if you can fix it than it would be great

**Comment by jgchristopher** [comment]
Arc doesn't currently support bookmarklets. That being said, I currently use Arc and I used [this site](https://sandbox.self.li/bookmarklet-to-extension/) to turn the bookmarklet generated from the plugin to an extension. 

I am going to work on just generating a chrome extension as part of the plugin as well. 

Thanks for the feedback.

**Comment by DutchPete** [comment]
Hi John, I also use Arc and would be interested to use your extension.

You say you turned he bookmarklet generated from the plugin to an extension: how is the bookmarklet generated? Should I just install the current Chrome extension? If so, whereabouts will I be able to find the bookmarklet?

**Comment by jgchristopher** [comment]
So I can't solve this within Obsidian, but I have an idea to make this more user friendly.

I am going to develop a web service to go along with this plugin that will generate browser extensions for a vault. There will be a link in the plugin settings that when clicked will call the service and download a .zip file of supported browsers. I will include instructions on how to enable the local browser extension.

**Comment by jgchristopher** [comment]
I just wanted to add an update on this. I am pretty close to getting this out. This will provide a link in the app to generate and download a Chrome-based browser extension that would work just like the bookmarklet.

**Comment by paranjay245** [comment]
aye cheers thank you soo much love you :)

**Comment by jgchristopher** [comment]
There is now a button to click that will generate a link to download a .zip file. This .zip file needs to be expanded. Then you can use `Manage Extensions` in Arc (or any Chrome-based browser), click the developer mode toggle in the top right, click the `Load unpacked` button, and select the unzipped folder. 

Still need to work on a better icon.

**Comment by paranjay245** [comment]
> 

damn man this is freaking insane assfuck :) loving it using 👍 ;)
