### ISSUE TITLE
FR: Allow customize the format of appended text.

### ISSUE THREAD

**Issue by lunakunada** [jgchristopher/obsidian-clipper#6]
I used[ another plugin ](https://github.com/jplattel/obsidian-clipper)before. This plugin is much stabler and I like it.

 I'm wondering if it is possiable for users to customize the format of appended text.

[Some reference](https://i.imgur.com/aWXlZZu.png)

**Comment by jgchristopher** [comment]
I have this on my road map. My plan was to allow a template to be used.

**Comment by jpfieber** [comment]
That would be awesome. Your plugin works very well, but doesn't display the text in a way that fits in my notes.  Being able to reconfigure (eg. Not a task, Add time to front like the Memos plugin, move Tag to front, don't use line afterwards) would put this plugin over the top!

**Comment by jgchristopher** [comment]
You can configure a template to define how the clipping should be formatted. I did add a {{time}} variable that can store date and time depending on how you format it.

I need to document this better.
