### ISSUE TITLE
Obsidian keeps opening

### ISSUE THREAD

**Issue by jok8** [jgchristopher/obsidian-clipper#69]
Hello, first of all thank you for this great plugin.
The only issue I found, on mobile as on desktop, was that Obsidian keeps opening after clipping, even when the specific option is is set on "NO" in settings.
Can you please investigate on this? Thanks

**Comment by jgchristopher** [comment]
Thanks, I will take a look

**Comment by jgchristopher** [comment]
Sorry, I misunderstood this request when I originally read it. 

The setting you are referring to "Open Note After Adding Clipper?" refers to if the specific note clipped to should open in obsidian and become the focus, not if Obsidian the application should open or not. 

I am 99% sure that I can't control if Obsidian opens/takes focus, but I will continue to investigate.
