### ISSUE TITLE
'Sort' order of Daily Notes entry

### ISSUE THREAD

**Issue by jpfieber** [jgchristopher/obsidian-clipper#9]
In 0.0.3, I just noticed that when I add Obsidian Memos, new entries go to the bottom of the list under the defined heading, but your clips go to the top of the list, so they're out of order.  Any chance to put them at the bottom, or provide a configuration for which you prefer?  Thanks!

**Comment by jgchristopher** [comment]
So, this is a challenge right now, and I will need to see how I can properly support this. 

The challenge is that a selection from a clipping could contain a heading entry, which makes programmatically finding where the configured heading section ends to append the next clipping. 

If you don't configure a heading, clippings are appended to the bottom of the document. You could accomplish your request  by not configuring a header and ending your periodic note template with your preferred heading, and the clippings would be appended after that. 

I will explore options for configuring a heading and appending rather than prepending.

**Comment by jpfieber** [comment]
Yea, appending may only be possible, or at least give predictable results, if you don't allow other headings in content.  If you just use it like my example in the discussion, which doesn't include content, then no problem, you can just look ahead to the next header.  Putting the content inside a blockquote would fix it, but then you lose all the original formatting, so not a great tradeoff. Hope you come up with a clever idea!

**Comment by jgchristopher** [comment]
I am playing with not allowing the passed in content to have any level 1 headings. I can just write any 'h1' elements as '##'. That could work.

**Comment by jpfieber** [comment]
That would help. As a point of reference, the 'Memo' plugin looks for ANY heading.

**Comment by jpfieber** [comment]
After giving it more thought, the type of layout I'm working with would be disrupted if ANY headings are injected. I think the best solution may be to provide an option to "Disable Headings" (which replaces ##, ###, ####, ##### and ###### in content with **) or provide a way for the user to decide what to replace each heading with (could be in the options page or could be via template).

This got me thinking, is it possible to generate multiple bookmarklets, each with it's own template/options?  Then one could have a 'clip to journal' bookmarklet that looks for the 'Journals' heading, and a 'clip full content' bookmarklet that looks for a different heading. Opens up a whole new way of clipping things.  You'd either have to store all the settings options in the template or in some kind of configuration file, or the options page would have to have the ability to 'add a new configuration' allowing you to set options and generate a new bookmarklet.  Anyway, something to think about!

**Comment by jgchristopher** [comment]
@jpfieber I am working on a change that will allow you to configure how headings are handled in the markdown transform from within the plugin settings within Obsidian. I will also add a template to control further formatting per location configured to save highlighted data. This should further help with your use case.  #12 and #13 are the tickets tracking this work.
